import Head from 'next/head';
import { Banner, Navbar, CardSection } from '../components';
import { getVideos, getPopularVideos } from '../lib/videos';

export async function getServerSideProps() {
  // const sciFiVideos = await getVideos('sci fi movies');
  // const actionVideos = await getVideos('action movies');
  // const popularVideos = await getPopularVideos();
  return {
    props: {
      sciFiVideos: [],
    },
  };
}

const Home = ({ sciFiVideos, actionVideos, popularVideos }: any) => {
  return (
    <div>
      <Head>
        <title>Shahid</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />
      <Banner
        id='lyy7y0QOK-0'
        title='Space Sweepers'
        subTitle='Sci-fi/Space opera'
        imgUrl='/static/space-sweepers.jpg'
      />

      {/*  <CardSection header='Sci-Fi' size='large' videos={sciFiVideos} /> */}
      {/* <CardSection header='Action' size='medium' videos={actionVideos} /> */}
      {/* <CardSection header='Popular' size='small' videos={popularVideos} />  */}
    </div>
  );
};

export default Home;
